# Enable C++ support
#language: cpp
language: c

os: linux

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make all

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
